apiVersion: v1
kind: Service
metadata:
  name: ngix-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - name: web
    port: 80
    targetPort: web
    nodePort: 31111
